# Configuration for tuning of the collider
config_collider:

  config_knobs_and_tuning:
    knob_settings:

      # Exp. configuration in IR1, IR2, IR5 and IR8***
      on_x1   : -145.000  
      on_sep1 :   0.0 #-0.550  
      phi_IR1 :  180.000  

      on_x2h  :    0.000  
      on_sep2h:    1.0 # 1.000  
      on_x2v  :  200.000  
      on_sep2v:    0.000
      phi_IR2 :   90.000  

      on_x5   :  145.000  
      on_sep5 :    0.0 # 0.550  
      phi_IR5 :   90.000  
      
      on_x8h  :    0.000  
      on_sep8h:   -0.01 #-1.000  
      on_x8v  :  200.000  
      on_sep8v:    0.000 
      phi_IR8 :  180.000  

      # Spurious dispersion correction
      on_disp  :    1.000  

      # Magnets of the experiments
      on_alice_normalized: 1
      on_lhcb_normalized: 1
      on_sol_atlas: 0
      on_sol_cms: 0
      on_sol_alice: 0

      # RF voltage and phases
      vrf400: 12.0 # [MV]
      lagrf400.b1: 0.5 # [rad]
      lagrf400.b2: 0. # [rad]

      # Octupoles
      i_oct_b1: 300. # [A]
      i_oct_b2: 300. # [A]

    closed_orbit_correction:
      lhcb1: correction/corr_co_lhcb1.json
      lhcb2: correction/corr_co_lhcb2.json

    # Tunes and chromaticities
    qx:
      lhcb1: 62.31
      lhcb2: 62.31
    qy:
      lhcb1: 60.32
      lhcb2: 60.32
    dqx:
      lhcb1: 5.0
      lhcb2: 5.0
    dqy:
      lhcb1: 15.0
      lhcb2: 15.0
    
    # Linear coupling
    delta_cmr: 0.001
    delta_cmi: 0.0

    knob_names:
      lhcb1:
        q_knob_1: dqx.b1_sq
        q_knob_2: dqy.b1_sq
        dq_knob_1: dqpx.b1_sq
        dq_knob_2: dqpy.b1_sq
        c_minus_knob_1: c_minus_re_b1
        c_minus_knob_2: c_minus_im_b1
      lhcb2:
        q_knob_1: dqx.b2_sq
        q_knob_2: dqy.b2_sq
        dq_knob_1: dqpx.b2_sq
        dq_knob_2: dqpy.b2_sq
        c_minus_knob_1: c_minus_re_b2
        c_minus_knob_2: c_minus_im_b2

  config_beambeam:
    bunch_spacing_buckets: 10
    num_slices_head_on: 11
    num_long_range_encounters_per_side:
      ip1: 25
      ip2: 20
      ip5: 25
      ip8: 20
    sigma_z: 0.0761
    num_particles_per_bunch: 1.15e11
    nemitt_x: 2.2e-6
    nemitt_y: 2.2e-6
    mask_with_filling_pattern:
      pattern_fname: /afs/cern.ch/work/c/cdroin/private/example_DA_study/master_study/run_2024/filling_scheme/25ns_2228b_2216_1686_2112_hybrid_8b4e_2x56b_25ns_3x48b_12inj.json
      i_bunch_b1: null # If not specified, the bunch with the worst schedule is chosen
      i_bunch_b2: null # Same. A value for i_bunch_b1 and i_bunch_b2 must be specified if pattern_fname is specified

  config_lumi_leveling_ip1_5:
      luminosity: 2.0e+34
      num_colliding_bunches: null # This will be set automatically according to the filling scheme
      vary:
        - num_particles_per_bunch
      constraints:
        max_intensity: 1.8e11
        max_PU: 70

  skip_leveling: false
  config_lumi_leveling:   
    ip2:
      separation_in_sigmas: 5
      plane: "x"
      impose_separation_orthogonal_to_crossing: false
      knobs:
        - on_sep2h
        - on_sep2v
      bump_range:
        lhcb1:
          - e.ds.l2.b1
          - s.ds.r2.b1
        lhcb2:
          - s.ds.r2.b2
          - e.ds.l2.b2
      preserve_angles_at_ip: true
      preserve_bump_closure: true
      corrector_knob_names:
        # to preserve angles at ip
        - corr_co_acbyvs4.l2b1
        - corr_co_acbyhs4.l2b1
        - corr_co_acbyvs4.r2b2
        - corr_co_acbyhs4.r2b2
        # to close the bumps
        - corr_co_acbyvs4.l2b2
        - corr_co_acbyhs4.l2b2
        - corr_co_acbyvs4.r2b1
        - corr_co_acbyhs4.r2b1
        - corr_co_acbyhs5.l2b2
        - corr_co_acbyvs5.l2b2
        - corr_co_acbchs5.r2b1
        - corr_co_acbcvs5.r2b1

    ip8:
      luminosity: 2.0e+32
      num_colliding_bunches: null # This will be set automatically according to the filling scheme 
      impose_separation_orthogonal_to_crossing: true
      knobs:
        - on_sep8h
        - on_sep8v
      constraints:
      - x_lhcb1_<_0_ip8
      # - x_lhcb2_>_0_ip8
      # - y_lhcb1_>_0_ip8
      # - y_lhcb2_<_0_ip8
      bump_range:
        lhcb1:
          - e.ds.l8.b1
          - s.ds.r8.b1
        lhcb2:
          - s.ds.r8.b2
          - e.ds.l8.b2
      preserve_angles_at_ip: true
      preserve_bump_closure: true
      corrector_knob_names:
        # to preserve angles at ip
        - corr_co_acbyvs4.l8b1
        - corr_co_acbyhs4.l8b1
        - corr_co_acbyvs4.r8b2
        - corr_co_acbyhs4.r8b2
        # to close the bumps
        - corr_co_acbyvs4.l8b2
        - corr_co_acbyhs4.l8b2
        - corr_co_acbyvs4.r8b1
        - corr_co_acbyhs4.r8b1
        - corr_co_acbcvs5.l8b2
        - corr_co_acbchs5.l8b2
        - corr_co_acbyvs5.r8b1
        - corr_co_acbyhs5.r8b1

# Configuration for the track job
config_simulation:

  # Collider file
  collider_file :    '../collider/collider.json'

  # Distribution in the normalized xy space
  particle_file:  '../particles/000.parquet'

  # Initial off-momentum
  delta_max  :    27.e-5   

  # Tracking
  n_turns    :    1000     # number of turns to track

  # Beam to track
  beam: 'lhcb1' #lhcb1 or lhcb2

# Save collider or not
dump_collider: false
dump_config_in_collider: false

# Log
log_file: 'tree_maker.log'